import { StyleSheet } from "react-native";
import * as CONST from "../Utils/constants";
import { StatusBar } from 'react-native';

export const LeaderBoardStyles = StyleSheet.create({
    header: {
        alignItems: 'center',
        flexDirection: 'row',
        marginTop: StatusBar.currentHeight || 0,
        marginHorizontal: "4%",
    },
    title: {
        color: CONST.HEADING2_COLOR,
        fontFamily: 'Inter-Bold',
        fontSize: CONST.responsiveHeight(32),
        lineHeight: CONST.responsiveHeight(39),
        letterSpacing: -0.005,
        textAlign: 'center',
        flex: 1,
        marginVertical: CONST.PRIMARY_VERTICAL_MARGIN,
    },
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        marginVertical: CONST.PRIMARY_VERTICAL_MARGIN,
    },
    campaignContainer: {
        width: "90%",
        height: "auto",
        borderRadius: CONST.responsiveWidth(30),
        backgroundColor: 'white',
        alignItems: 'center',
        paddingVertical: CONST.PRIMARY_VERTICAL_MARGIN,
        elevation: 15,
        shadowColor: CONST.DARK_PINK_COLOR,
        shadowOffset: { width: CONST.responsiveWidth(-4), height: CONST.responsiveHeight(-2) },
        shadowOpacity: 0.7,
        shadowRadius: CONST.responsiveWidth(30),
        paddingHorizontal: CONST.PRIMARY_VERTICAL_MARGIN,
        marginBottom: CONST.PRIMARY_VERTICAL_MARGIN,
    },
    campaignTime: {
        color: CONST.MEDIUM_PINK_COLOR,
        fontFamily: 'Inter-Medium',
        fontSize: CONST.responsiveHeight(20),
        letterSpacing: 0,
        textAlign: 'center',
        marginVertical: CONST.PRIMARY_VERTICAL_MARGIN,
    },
    top3Containers: {
        flexDirection: 'row',
        justifyContent: 'space-evenly',
    },
    top1Container: {
        alignItems: 'center',
        marginHorizontal: "-1%",
        flex: 1,
    },
    top2Container: {
        alignItems: 'center',
        marginHorizontal: "-1%",
        flex: 1,
        marginTop: CONST.responsiveHeight(40),
        marginBottom: CONST.PRIMARY_VERTICAL_MARGIN,
    },
    subContainerTop: {
        width: "90%",
        alignItems: "center",
        flexWrap: 'wrap',
    },
    subContainer: {
        paddingTop: CONST.responsiveHeight(15),
        paddingBottom: CONST.responsiveHeight(15),
        flexDirection: "row",
        alignItems: "center",
        marginRight: CONST.responsiveWidth(20),
    },
    item: {
        flexDirection: 'row',
        alignItems: "center",
        marginHorizontal: "6%",
        justifyContent: 'space-between',
    },
    userItem: {
        elevation: 4,
        shadowColor: CONST.HEADING2_COLOR,
        shadowOffset: { width: CONST.responsiveWidth(0), height: CONST.responsiveHeight(4) },
        shadowOpacity: 0.5,
        shadowRadius: CONST.responsiveWidth(10),
        backgroundColor: CONST.LIGHT_PINK_COLOR,
        borderRadius: CONST.responsiveWidth(10),
    },
    rank: {
        fontFamily: 'Inter-Light',
        fontSize: 12,
        letterSpacing: 0,
        textAlign: 'center',
        color: CONST.DARK_GREEN_COLOR,
    },
    starIcon: {
        width: CONST.responsiveWidth(25),
        height: CONST.responsiveWidth(25),
        alignItems: 'center',
        justifyContent: 'center',
    },
    username: {
        fontFamily: 'Inter-Medium',
        fontSize: CONST.responsiveHeight(16),
        lineHeight: CONST.responsiveHeight(19),
        letterSpacing: 0,
        color: CONST.NAVIGATION_ACTIVE_COLOR,
    },
    usernameTop: {
        fontFamily: 'Inter-Medium',
        fontSize: 16,
        textAlign: 'center',
        letterSpacing: 0,
        color: CONST.NAVIGATION_ACTIVE_COLOR,
    },
    score: {
        marginLeft: CONST.responsiveWidth(30),
        fontFamily: 'Inter-Medium',
        fontSize: CONST.responsiveHeight(16),
        lineHeight: CONST.responsiveHeight(19),
        letterSpacing: 0,
        color: CONST.FEATURE_TEXT_COLOR,
    },
    scoreTop: {
        color: CONST.DARK_PINK_COLOR,
    },
    avatar: {
        width: CONST.responsiveWidth(30),
        height: CONST.responsiveWidth(30),
        borderRadius: CONST.responsiveWidth(15),
        marginHorizontal: CONST.responsiveWidth(20),
    },
    avatarTop1: {
        width: CONST.responsiveWidth(100),
        height: CONST.responsiveWidth(100),
        borderRadius: CONST.responsiveWidth(50),
        zIndex: -1,
    },
    avatarTop2: {
        width: CONST.responsiveWidth(80),
        height: CONST.responsiveWidth(80),
        borderRadius: CONST.responsiveWidth(40),
        zIndex: -1,
    },
    separator: {
        borderBottomWidth: 1,
        borderBottomColor: '#C4C4C4',
    },
});